### PR TITLE
Implementing CTRL + Arrows to move to next/previous word

### PR DESCRIPTION
**Pull request by carol-mb**
This pull request implements the functionality for CTRL + Arrow to move to next/previous word.
Issue: https://github.com/UPB-CS-OpenSourceUpstream/kibi/issues/3

### CODE REVIEW

**Comment by alexandruradovici** [comment]
This needs to be formatted with `cargo fmt`, you will have to find another way to reduce the number of lines of code.

**Comment by carol-mb** [comment]
If I run `cargo fmt` some brackets will open up resulting a lot of new lines.
I tried to merge some lines using tuples to make more space.

**Comment by alexandruradovici** [comment]
> If I run `cargo fmt` some brackets will open up resulting a lot of new lines. I tried to merge some lines using tuples to make more space.

It's use is mandatory.

**Comment by carol-mb** [comment]
I found in the closed PR that I could run `cargo +nightly fmt`.

**Comment by alexandruradovici** [comment]
Please write a pull request message and send the pull request to upstream. Post a link to it in this PR.

**Review by alexandruradovici — APPROVED** [review]

**Comment by carol-mb** [comment]
I synced my branch with master because it was behind with 1 commit, hope that is not a problem.
Thank you for help! I opened the pull request to upstream: https://github.com/ilai-deutel/kibi/pull/214

**Comment by alexandruradovici** [comment]
Merged to upstream.

**Comment by alexandruradovici** [comment]
@carol-mb Please select a timeslot for the interview https://doodle.com/meeting/participate/id/eZ8gOOEb.

**Pull request closed without merging**
